sonar.projectKey=resopay-order-service
sonar.projectName=ResoPay Order Service
sonar.projectVersion=1.0
sonar.sources=src
sonar.tests=tests
sonar.language=js
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000
sonar.token=sqp_0e936c4e9d2b37aeb753d3e9689d537458c0ce0d
sonar.javascript.lcov.reportPaths=coverage/lcov.info